### ISSUE TITLE
Issues and features requests

### ISSUE THREAD

**Issue by Lejomoz** [ysard/cookie-quick-manager#1]
Hello ysard, i think I'm the first person to use your addon  :D

The appearance looks good, and i think it has the potentiality to become a popular extension. However, as it's still in beta phase, it has some issues that i would like to point them out to you...

1- The "Export" and "Import" options are always greyed out and doesn't work at all.

2- The frame window doesn't remember the size. i have a small monitor, and i must adjust the CQM window every time i start it to be able to use it.

3- When ticking Sub-domains, you must manually refresh to see the changes. (not sure if that intended, but would be much nicer if the list refreshed automatically)

and some features i would like to see in CQM...

1- Ability to (whitelist/protect) some cookies from deletion, with an option in QCM toolbar icon menu to remove the non protected cookies.

2- in the domains column, the up/down arrow keyboard buttons scroll the list. would be better if they are adjusted to select the previous/next cookie.

3- Removing the subdomain items from domains list when ticking Sub-domains as it become already included in the domain's cookies itself.

that's all for now. and thank you for your work.

**Comment by ysard** [comment]
Hello, first of all, thank you for your encouraging comments and suggestions!
I'm working on implementing the majority of them; 
I'm reacting quickly to some of them:
- The "Export" and "Import" items in the export menu are always greyed because they are only headers of the 2 sections. This menu is unclear, I'll work on it again.
- The memorization of the window size should be available at the same time as a tab "options" to store personal settings (whitelist etc.).
- The protection of the deletion of some cookies seems to me to be the only one rather difficult to implement in the short term.

Thank you again.

**Comment by Lejomoz** [comment]
Hi again ysard,

I'm using the latest beta now, and i would like to thank you for listening to me  :)

but still the issue of remembering the window's size. i see you tried to do something with it from the commits list, but it doesn't seem to solve it.

another minor issue...  when you click "Search cookie for" it does search by the domain name without the dot. so for example,  if i'm on a site like www.rt.com and used this feature, it will show cookies for rt.com and deviantart.com.

and for the things i would like to see in the next versions, an option to export all cookies? and of course the cookie protection, i hope you will be able to figure it out.

and thank you for your great work.

**Comment by ysard** [comment]
Hi, im actually working ont it, thank you for your review ;)
About your window size problem: What size do you expect for it ? Below 768x585 the default size is set.
Although the window adapts to smaller sizes, it seems to me that the user experience is strongly degraded...

The last version is 0.1rc1 on the public channel, maybe you took the last version of the beta chanel which is the 0.1beta6 without the update. 

The cookie protection is quite unpredictable. The only way I have to detect a modification is to listen to events sent after these modifications are made by the browser. So by rewriting the old cookie just after the reception of the event, I have doubts about the real effectiveness of the action if an application tries to read the cookie in this short interval of time. To test... ;)

**Comment by Lejomoz** [comment]
The default size is 768x585? i don't think QCM follow that setting. i have a resolution 1024x768, and every time i start QCM, i have to adjust the frame's width because it's exceeding the screen. and the height too, to be able to see the search form and the bottom buttons. and the version i use is 0.1rc1.

About the cookie protection... i meant protection from deletion not modification _(i don't know if that's even possible. i once tried an add-on which claimed to do that and make the cookie read-only but it didn't work_)  but if you can do that too, that definitely would be great  :)

**Comment by ysard** [comment]
Hi,
ok il will test that on a small resolution. At this time the cookie protection seems to be finished as well as the addition of the export function for all cookies :)

**Comment by Lejomoz** [comment]
How can i use the protection feature? it's isn't obvious to me. (_i hope it's isn't because my stupidity like the export/import thing :D_)

Plus, there's a problem when importing cookies from file, it gives me an error "SyntaxError:JSON.parse" if a cookie value have a quotation mark in it. i think you should escape those special characters when exporting.

**Comment by ysard** [comment]
Thanks for the bug reports :D

- I've changed the tooltip about the protection feature: When the padlock is closed you can click on it and prevent the future deletion of this cookie; So, the padlock will be opened, which means that it allows the user to remove the protection by clicking on it.

- I've corrected the double quotes error; well seen.

- Indeed, the cookie count is global... I will try to change that :p

**Comment by ysard** [comment]
About the bug in the search function:
I could easily be more strict in the search results but at the moment it would mean knowing by heart what you are looking for.
Ex: devianart. com, devianart. fr?
Currently you can just search "devian" and you will have some results instead of nothing...
I prefer recall over precision in this case :)

**Comment by Lejomoz** [comment]
I still get the "SyntaxError:JSON.parse" with 0.1rc5, because of those two lines...

>   "Content": "\"{\\"time\\": 1514931619\054 \\"0.0.0.0\\": 8452}:1eWUwC:12YvWC8cCZsOzmdM-gAy9hCMD14\"",
>   "Content": "a:4:{i:0;s:5:"45220";i:1;s:40:"7c9b4b20ddf1b97716512e93cd83868e486ee07d";i:2;i:1602258891;i:3;i:0;}",

  
And about cookies protection... 
I think to make users takes full advantage of cookies protection, is to give them an option to remove all the cookies except the protected ones they want to be always there. either as a button in QCM windows, or the toolbar icon menu, or on firefox exiting, or all of them.  :)

**Comment by ysard** [comment]
Ok, these lines are not in a correct JSON format due to my incorrect code (fixed yesterday). You should re-export or escape the double-quotes yourself in this file (sorry).
Okay, I'll put shortcuts to erase all cookies at once.

**Comment by Lejomoz** [comment]
They are exported with the newer version. for the first line, i think you have to escape the backslash too (and other JSON's special characters) because the cookie value itself has an escaped quote mark.

The second line, it got exported without escaping the quotation mark. i don't know why.

**Comment by Killogy** [comment]
About cookies protection, I was looking for a **biscuit** addon replacement https://addons.mozilla.org/es/firefox/addon/biscuit-220876/

As **Lejomoz** said before, will be nice if cookies protection (Padlock) preserves specific cookies from being removed. 

I was excited to see how cookies were not removed when padlock was open for specific cookies, but... the cookie protection is not working as I expected, If I press the padlock to open it, then I can´t delete the cookie either through Firefox cookie manager or your Addon, (same as biscuit it does), but when Firefox is restarted, the paddock is closed and cookies can be removed.

Can you fix this issues?, can you make cookie protection option a permanent protection for cookies between Firefox sessions, as **biscout** addon it does?.

I like to preserve specific cookies and when I press the button **"Remove all cookies"** only preserve ones remain in cookie manager. With you **protection cookie** feature, working between Firefox session, we will get this goal.

**Comment by ysard** [comment]
@Lejomoz : The problem will be fixed in the next release, sorry fort that :)

@Killogy : Hi, thank you for your report;
- The non-memorisation of the protection is not an expected behavior. I will try to fix that in the next release.
- Good idea, I will provide an option to delete everything when closing the browser.

**Comment by Lejomoz** [comment]
Hello again ysard,

For the importing issue,  the cookies in the previous examples has been solved, thank you. but i got a JSON.Error with a new cookie and it has special characters in the name raw this time.

	"Name raw": "secureid//\*\\&Ã©Ã r",
	
	
For the cookie protection, two issues...

- I use version 0.1rc6 and it still doesn't remember the cookie's protection state.

- The second issue is weird, and i hope i can explain it well to you...

    When i use the delete all button to remove all the unwanted/unprotected cookies, it does the job very well. the unwanted cookies gets removed and the protected ones remains. BUT, closing the browser and reopening it, those protected cookies which was existing when the delete button was used (and only those cookies) will be removed!

last thing, i don't know the open source rules, but is this your code? and is he allowed to do that? it's even with the same bugs ¯\\_(ツ)_/¯
https://addons.mozilla.org/en-US/firefox/addon/cookie-manager-pro

**Comment by Killogy** [comment]
I don´t know why my review on firefox has been deleted.

Anyway, there I explained why cookies´s protection is not saved on firefox restart, I needed to delete the folder d:\Users\YOUR-USERNAME\AppData\Roaming\Mozilla\Firefox\Profiles\YOUR-FIREFOX-PROFILE\browser-extension-data\{60f82f00-9ad5-4de5-b31c-b16a47c51558} Then addon will save cookie´s protecction state.

**Comment by Lejomoz** [comment]
@Killogy Hmmm, that seems to work now for me, but the second issue still occurring to me. have you tried to use the delete all button? and does the protected cookies remain after that with a new firefox session?

**Comment by Killogy** [comment]
Yes it is working for me.

I pressed the button "delete all the cookies" then closed addon preferences tab then restarted firefox and all protected cookies are there, it is working properly for me.

**Comment by ysard** [comment]
# About the protection bug
This is due to the fact that the wrong configuration file is already in storage when the update is done.
Delete the folder allows you to start over from scratch; the next version ensures that the options in storage.js are correctly written (see f0649d9), even if the previous one is wrong.

# About the loss of commentary
A priori this happens (see [discourse.mozilla.org](https://discourse.mozilla.org/t/disappearing-negative-reviews-for-ghostery-add-on/7811/11))... in any case I didn't have anything to do with it :( Maybe you it will be possible to repost it tomorrow by mentioning that the previous comment disappeared without reason.

# About the Cookie Manager Pro
I saw him this afternoon:
- Yes it is a violation of the GPL license;
...and I started auditing it:
- It is a copy with a quick redesign; the code is exactly the same EXCEPT for a malicious script inserted in all the consulted web pages whose purpose is to redirect the visitors of e-commerce websites on affiliate links...
A manual reviewing of the addons is in progress, the guy is unlikely to get away with it. Let's hope this will be quick.
Cf: [discourse thread](https://discourse.mozilla.org/t/copy-of-addon-violation-of-license-and-insertion-of-malicious-code-what-can-i-do/24252/2).
In any case thank you for reporting it to me :)

**Comment by Killogy** [comment]
@ysard Sometimes when I´m browsing a website a number on the toolbar icon appear, what does this number mean?

For example, I have 200 protected cookies, this number appear when I press the button **"Delete all the cookies"** the number is same as the number or protected cookies I have. it´s bugged because if I click the **"Delete all the cookies"** again, the number increases again by 200,  it's annoying.

Sometimes when i´m visiting some website a lower number appear, like 6 or so, and this number stay there even if I close the tab or stops visiting the website, I don´t know what is the meaning of this number, **the number of protected cookies I have of that specific domain?**.... If I visit another website with protected cookies, the number doesn´t show, So definitely I don't know the meaning.

Can you add some tip or explication and some option **to show/ do not show this number?** or show this number in the **ToolTips** when mouse hover the toolbar icon.

**Comment by Killogy** [comment]
There is a problem importing cookies with special character, when cookie content has  **/** special character, I need manually add another **/**.

For example, error importing.

	"Content": "\"eyJfdXNlciI6WzYyODY5MDIyXTIwMTE2MjAsMSwiS3FnRVFLYkonSVVnQVdIQnZvcVVlSiIsMTUxNTYyNDc5MSwxNTE1NjYyNjEzXX0**\**075|1515664135|3f7c5a63d217c3f0be95b5e246439bdcb579029c\"",
	"Content raw": "\"eyJfdXNlciI6WzYyODY5MDIyXTIwMTE2MjAsMSwiS3FnRVFLYkonSVVnQVdIQnZvcVVlSiIsMTUxNTYyNDc5MSwxNTE1NjYyNjEzXX0**\**075|1515664135|3f7c5a63d217c3f0be95b5e246439bdcb579029c\"",

Importing cookie correctly:

	"Content": "\"eyJfdXNlciI6WzYyODY5MDIyNTIwMTE1MjAsMSwiS3FnRVFLYkpnSVVnQVdIQnZvaVVlSiIsMTUxNTYyNDc5MSwxNTE1NjYyNjEzXX0**\\**075|1515664135|3f7c5a63d217c3f0be95b5e246439bdcb579029c\"",
	"Content raw": "\"eyJfdXNlciI6WzYyODY5MDIyNTIwMTE1MjAsMSwiS3FnRVFLYkpnSVVnQVdIQnZvaVVlSiIsMTUxNTYyNDc5MSwxNTE1NjYyNjEzXX0**\\**075|1515664135|3f7c5a63d217c3f0be95b5e246439bdcb579029c\"",

Another problem is when importing protected cookies, they lost protection setting, so we need to set the protection again for all the cookies, (200 for me). Can you fix this? or can you add a button to set protection for all cookies, so when the list of cookies is imported, we can set the protection for all cookies simpy by pressing the **"protect all the cookies"**, so we don´t  need set the protection by hand one by one.

**Comment by ysard** [comment]
@Killogy Sometimes when I´m browsing a website a number on the toolbar icon appear, what does this number mean?
It is the global counter (on all the tabs) of all protected cookies that were restored when something tries to delete them.
This alert is currently confusing, I will remove it (temporarily at least) in rc7 :p

@Killogy  & @Lejomoz : About the incorrect export. In theory it is fixed now in rc7.
Thanks to you for testing all this.
Note: The host and path fields remain unprotected, but this is based on the fact that these elements do not normally have the characters in question (\, ")...

@Killogy : when importing protected cookies, they lost protection setting, so we need to set the protection again for all the cookies.
Ok i see the problem; I will try to save the protection status in the json, and add an option to protect all cookies during an import. To see in rc8 :p

**Comment by ysard** [comment]
Hi,
a new release 0.2b5 is available for testing with many fixs in the beta channel:
https://addons.mozilla.org/fr/firefox/addon/cookie-quick-manager/versions/beta

**Comment by Lejomoz** [comment]
> > 
> 
> The second issue is weird, and i hope i can explain it well to you...
> 
> When i use the delete all button to remove all the unwanted/unprotected cookies, it does the job very well. the unwanted cookies gets removed and the protected ones remains. BUT, closing the browser and reopening it, those protected cookies which was existing when the delete button was used (and only those cookies) will be removed!

I still have this problem. and to revise it, any attempt to delete a protected cookie cause removing of expiration date, and the cookie becomes a session.

And it seems to be occurring only to me and i can't figure why. i even made a new profile to test QCM alone to see if the problem caused by conflicted settings with other addons, but still no solution.

Aside note: the hacker style... good play. i always find it amusing when i see the thieves getting robbed :D

**Comment by ysard** [comment]
@Lejomoz : Well seen. There were apparently two superposed bugs.
I forgot to put the expiration date back in cookies restored after deletion. Thus, session cookies were deleted when the browser was closed.
It is fixed in 6c75eeb and it will be fixed in next release.

And yes the Hacker style is a kind of vengeance :D

**Comment by Killogy** [comment]
@Lejomoz  @ysard , About Why all imported protected cookies are imported unprotected?, I tested it deeply, is because the addon only add the line **"import_protected_cookies":true,** when you mark the checkbox **Import cookies as protected cookies** in the preferences window in the file **storage.js**, addon should add the line **"protected_cookies":{}}** too . this last line is added to the file when you protect a cookie, only if this part is created the imported file with protected cookies will be imported with the cookies protected status.

So, even if you has checked **Import cookies as protected cookies** in the preferences window, remember to mark a cookie as protected, then delete all cookies close the addon window, open it again and then import the file with your protected cookies, all your cookies will imported with protected status.

Ya, everytime the button **delete cookies from the selected domain** or **delete all the cookies** is pressed, all cookies become a session cookie, they lost custom expirate date.

Can you add a **back** button in the settings page to go back to the cookie manager window?

Can you add a button to unprotected all the cookies?

And a big thanks to you for your mention in the "about" page.

P.S: A few days ago I reported the hacker user cloned addon, now his account has been deleted :D

**Comment by Lejomoz** [comment]
@Killogy 
> Ya, everytime the button delete cookies from the selected domain or delete all the cookies is pressed, all cookies become a session cookie, they lost custom expirate date.

Oh man, you made me think it's occurring to me only. which was about to make me insane, and made me question everything (my CQM preferences, my firefox, my OS system, my PC, and me as a human being) :D

@ysard: a minor issue, when you delete a cookie with "Delete cookies from selected domain" the selector goes to the top of the list, i think it would be better if the selector goes to the above cookie instead.

And if you are still open for features requests and didn't get bored yet... you may think of an option in the toolbar icon menu to remove cookies from the current website? i already use an addon for that, but it would be great if CQM could handle anything related to cookies.

**Comment by Killogy** [comment]
@Lejomoz  I told you I never had any problems with cookies gets deleted on browser restart, never happened to me.  I did not realize the problem of the loss of expiration date.

Yesterday, testing the issue about losing custom expiration date and cookies losing protection status when importing. On browser restart addon do not load cookies list sometimes, you need to press refresh button and your cookies will appear, maybe this explain your issue about cookies protected deleted on browser restart, maybe they do not gets deleted, simply addon is not loading them and you need to press refresh button. This problem happened to me only in a new firefox profile and only few cookies stored, never happened in my current firefox profile with many cookies stored, addon is loading cookies list properly.

**Comment by ysard** [comment]
Hi, 
I'm sorry for any problems with the import of protected cookies. That seems to be resolved now.
- The expiration date bug is fixed.
- A button to protect/unprotect all the cookies has been added.
- When a domain is removed, the top domain is now selected.

The malicious copy has been removed because of complaints/records + DMCA report. It took a little over a week.

@Killogy: About the empty list, I faced a similar problem when deleting cookies at startup. The API is not available immediately and the addon receives 0 cookie.
This is not the only example where Firefox 57 is very very fast compared to Firefox 56 on which I mainly develop.

Changes are now uploaded on the standard channel with the version 0.2rc1 :)

**Comment by Killogy** [comment]
Thanks for the update, I´m on Firefox 56.0.2 too.

I forgot to mention about some "special" cookies, these cookies are not detected by cookies manager extensions as yours and cookie manager+, then I need to export them manually through Firefox cookie manager.

for example.. https://addons.mozilla.org cookies like...

:{HOST}                         **{ISDOMAIN_RAW}**   {PATH}  **{ISSECURE_RAW}**  {EXPIRES_RAW}   **{NAME}**	     {CONTENT}
gro.allizom.snodda.:https:443	    **TRUE**	      /	       **FALSE**	          0	   **visitor-amo_home_promo_seen**        5

gro.allizom.snodda.:https:443	TRUE	      /	       FALSE	          0	   visitor-seen_impala_first_visit     1
gro.allizom.snodda.:https:443	TRUE	      /	       FALSE	          0	   visitor-seen_try_new_frontend       1

HOST name is under label **Scope** in the firefox cookie manager instead **Host** label

These cookies are under **addons.mozilla.org** but its HOST name is inverted, these cookies can´t be detected by addon exptensions so we can´t export them, only through Firefox cookie manager.  There are many domains storing this kind of cookies.

**Comment by Lejomoz** [comment]
@ysard using version 0.2rc1 and following your tip regarding "Delete all cookies on restart" to tick the "Clear history when Firefox closes" option, deletes all cookies including the protected ones. but CQM deletion works well though.

**Comment by ysard** [comment]
@Lejomoz , yes the native API has priority over the webextensions API.. So, cookies are deleted at the last moment while the addon is already unloaded.
Similarly by deleting unprotected cookies at startup, with the addon, I can not guarantee that some requests using these cookies have not already been made.
Security vs functionality...
Maybe i will write a proper tip...

**Comment by ysard** [comment]
@Killogy : about the inverted cookies: at first I thought you were joking :D But indeed these keys are stored in webappsstore.sqlite and play the role of cookies... I will look at what they are and what they really do...

**Comment by Killogy** [comment]
@ysard Protection cookies feature has stopped working for me.

I have all cookies protected with **biscuit** addon and **Cookie quick manager**, Steam cookies --> **Steamcommunity** and **store.steampowered.com** cookies protected only with **cookie quick manager**, when I restart Firefox Steam cookies gets deleted, I have to import him to preserve login in on steam. If I protect Steam cookies with biscuit addon, cookies are preserved between Firefox restarts.

I´m using latest addon version

**Comment by Lejomoz** [comment]
@ysard I can't use the up/down arrows to go through the list under the "Cookie" section. when using them, it moves through the list under the "Domains" section. is that a bug?

**Comment by ysard** [comment]
@Lejomoz : No it isn't a bug; currently you have to press Ctrl+Left or Ctrl+Right to switch between the 2 lists :p

**Comment by Lejomoz** [comment]
My bad indeed, i never looked at the shortcuts tab in the setting page. and i bet many users will get just as confused as i did  :D
but i wonder why CQM can't auto switch depending on the last selected item?

**Comment by Lejomoz** [comment]
@ysard One more feature request (_last one i swear :D_)

A unique color for protected cookie in the "Cookies" list similar to the expired ones, or maybe a small locker icon beside them.

**Comment by rbro** [comment]
Thanks for a nice extension.  Hopefully a quick question - should protecting a cookie preserve it even if the cookies are deleted in the browser?  I noticed that if I protect a cookie, and then clear my browser history for time range "Everything", all the cookies get deleted, even the cookies I marked to protect.  Should those protected cookies have been preserved with how I'm doing it?

**Comment by Killogy** [comment]
@rbro if you use native Firefox clear history, all cookies get deleted even if are protected by extension.

You need deactivate native Firefox **cookies clear option**, and use **extension delete all cookies on restart** option. Open extension Options page, under settings tab, check the box **delete all cookies on restart**.

> Due to limitations (the deletion occurs 2 seconds after restarting the browser), you will probably want to use the official option of Firefox: Preferences/Privacy & security, section History. Set Firefox will to Use custom settings for history, then select the checkbox for Clear history when Firefox closes. Beside Clear history when Firefox closes, click the Settings… button. The Settings for Clearing History window will open. Finally put a check mark next to cookies.
> Please note that the native option of Firefox will delete all the cookies even if they are protected.

**Comment by ysard** [comment]
Hi, I have less time to invest but:
@Lejomoz : There will be an indicator for protected cookies.
@rbro : The browser uses a different internal API when you delete cookies from settings or on restart.
So no signal is emitted and my addon can not restore for the moment a cookie in this case. I will work on it later when First Party Isolation and containers will be fully implemented.

Finally you can use the [umatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/) addon to delete session cookies at regular intervals, or refuse to write them according to very specific firewall rules. This is, in my opinion, a must have with ublock origin.

**Comment by rbro** [comment]
@Killogy and @ysard Thanks for your feedback.  I was trying to get similar functionality as the extension biscuit where protected cookies were preserved even when deleting them through the browser.  Does browser.cookies.onChanged.addListener not get called when deleting them through the browser?

**Comment by ysard** [comment]
@rbro
Apis are not called in the early stages of Firefox startup. Moreover https://developer.mozilla.org/en/Add-ons/WebExtensions/API/browsingData/removeCookies is an API that does not emit this event.
The webextensions APIs are young and probably deserve more maturity...

One solution might not be protected (not just their names) in a separate database. But the purpose of the addon is not to rewrite the full Firefox's cookie management...

**Comment by ysard** [comment]
I close this issue opened in the early days of the project
